# Generated by Django 4.1.13 on 2025-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='doc_file',
            field=models.FileField(default='', upload_to='fileuploads/'),
        ),
    ]
