# Generated by Django 4.1.13 on 2025-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_comment_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LW', 'Low'), ('MM', 'Medium'), ('HH', 'High'), ('CL', 'Critical')], default='MM', max_length=2),
        ),
    ]
