# Generated by Django 5.2.4 on 2025-07-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='usertyoe',
            new_name='usertype',
        ),
    ]
