# Generated by Django 5.2.4 on 2025-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_usertyoe_activitylog_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docfile',
            field=models.FileField(default='', upload_to='project/'),
        ),
    ]
